name: yaaw greet
description: Yet another actions workflow - greet

inputs:
  person:
    description: "Person to greet"
    required: true
    default: "World"

runs:
  using: node20
  main: src/index.js
