name: Test-ts

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: Build greet-ts action
        run: |
          cd greet-ts
          npm ci
          npm run build
          cd ..

      - uses: ./greet-ts
        with:
          person: "You"
